### ISSUE TITLE
Not working in Safari Version 17.0 (19616.1.27.111.16)

### ISSUE THREAD

**Issue by iKL3W** [mxmlndml/Bing-Chat-for-Safari#2]
Hello, on macOS Sonoma I couldn't use Bing Chat, even after installing everything as explained. The userscripts is detected by none action is taken. I have the pop-up still (maybe a new version of the pop up ?). Is it only me?
<img width="1552" alt="Screenshot 2023-09-22 at 18 33 57" src="https://github.com/mxmlndml/bing-chat-for-safari/assets/75533129/5d7af7b9-b47c-494b-8460-ff3b7ffbf059">

**Comment by mxmlndml** [comment]
Indeed, they changed the popup. I adapted the code for the new one, but since I'm still on macOS Ventura, I did only test it with Safari 16. Just reopen the issue, if the problem persists. And thanks for the feedback :)

**Comment by iKL3W** [comment]
works great! Thanks for the quick update!
